# Generated by Django 5.2.4 on 2025-07-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_response_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='is_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
