# Generated by Django 5.2.4 on 2025-07-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_response_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
