# Generated by Django 5.2.4 on 2025-08-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_category_alter_ad_content_alter_ad_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriber',
            new_name='user',
        ),
    ]
