# Generated by Django 5.2.4 on 2025-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(verbose_name='Текст отклика'),
        ),
    ]
