# Generated by Django 5.2.4 on 2025-08-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_response_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': [('can_send_mass_email', 'can_send_mass_email')]},
        ),
    ]
